/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    products: Product;
    categories: Category;
    media: Media;
    documents: Document;
    quotes: Quote;
    'project-gallery': ProjectGallery;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    'project-gallery': ProjectGallerySelect<false> | ProjectGallerySelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'site-content': SiteContent;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'site-content': SiteContentSelect<false> | SiteContentSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  slug: string;
  category: number | Category;
  /**
   * Short summary for product listings
   */
  excerpt?: string | null;
  description?: string | null;
  priceRange?: {
    from?: number | null;
    to?: number | null;
    /**
     * e.g., "From $120,000" or "Contact for pricing"
     */
    label?: string | null;
  };
  status?: ('draft' | 'active' | 'discontinued') | null;
  heroImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        category?: ('exterior' | 'interior' | 'detail' | 'lifestyle') | null;
        id?: string | null;
      }[]
    | null;
  floorPlans?:
    | {
        image: number | Media;
        /**
         * e.g., "Ground Floor", "First Floor"
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  dimensions?: {
    /**
     * Overall length in millimetres
     */
    length?: number | null;
    /**
     * Overall width in millimetres
     */
    width?: number | null;
    /**
     * Overall height in millimetres
     */
    height?: number | null;
  };
  bedrooms?: number | null;
  bathrooms?: number | null;
  /**
   * Total floor area in square metres
   */
  floorArea?: number | null;
  /**
   * Transport weight in kg
   */
  weight?: number | null;
  /**
   * e.g., Light gauge steel frame
   */
  structuralSystem?: string | null;
  insulationRating?: string | null;
  /**
   * National Construction Code building classification
   */
  nccClassification?: ('1a' | '1b' | '2' | '3' | '10a') | null;
  /**
   * AS/NZS 1170.2 wind region classification
   */
  windRegion?: ('A' | 'B' | 'C' | 'D') | null;
  /**
   * Bushfire Attack Level rating (AS 3959)
   */
  balRating?: ('BAL-LOW' | 'BAL-12.5' | 'BAL-19' | 'BAL-29' | 'BAL-40' | 'BAL-FZ') | null;
  /**
   * States and territories where this product is approved for installation
   */
  applicableStates?: ('NSW' | 'VIC' | 'QLD' | 'SA' | 'WA' | 'TAS' | 'NT' | 'ACT')[] | null;
  certifications?:
    | {
        name: string;
        type?: ('structural' | 'electrical' | 'plumbing' | 'fire-safety' | 'energy-efficiency' | 'other') | null;
        document?: (number | null) | Document;
        issueDate?: string | null;
        expiryDate?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Group options into categories (e.g., Exterior Finish, Flooring)
   */
  optionCategories?:
    | {
        categoryName: string;
        selectionType?: ('single' | 'multiple') | null;
        options?:
          | {
              name: string;
              description?: string | null;
              image?: (number | null) | Media;
              /**
               * Additional cost for this option (can be negative for downgrades)
               */
              priceModifier?: number | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Exported scene graph from Pascal Editor. Upload the JSON file contents here.
   */
  sceneTemplate?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 2D preview image of the module for the Site Planner sidebar (400x300 recommended)
   */
  templateThumbnail?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  /**
   * Lower numbers appear first
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility and SEO
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  documentType?: ('compliance' | 'specification' | 'brochure' | 'other') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: number;
  referenceNumber: string;
  /**
   * Where this quote originated
   */
  source?: ('product-page' | 'planner' | 'contact' | 'general') | null;
  status?: ('new' | 'pending' | 'responded' | 'won' | 'lost') | null;
  product?: (number | null) | Product;
  /**
   * Snapshot of product title at time of quote
   */
  productTitle?: string | null;
  productSlug?: string | null;
  /**
   * JSON snapshot of selected configuration options
   */
  selectedOptions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * BOM array: { productId, productTitle, quantity, dimensions, floorArea }[]
   */
  layoutData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 3D layout screenshot from Site Planner
   */
  layoutScreenshot?: (number | null) | Media;
  interestCategory?: ('modular-homes' | 'kit-homes' | 'container-homes' | 'tiny-homes' | 'sheds' | 'other') | null;
  contactName: string;
  contactEmail: string;
  contactPhone?: string | null;
  company?: string | null;
  quantity?: number | null;
  deliveryState?: ('NSW' | 'VIC' | 'QLD' | 'SA' | 'WA' | 'TAS' | 'NT' | 'ACT') | null;
  /**
   * City/region for delivery
   */
  deliveryLocation?: string | null;
  projectTimeline?: ('immediate' | 'short' | 'medium' | 'long' | 'exploring') | null;
  /**
   * Site access, terrain, services availability, etc.
   */
  siteConditions?: string | null;
  isEstateInquiry?: boolean | null;
  numberOfUnits?: number | null;
  siteAddress?: string | null;
  /**
   * Array of {model, quantity} pairs
   */
  modelMix?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  additionalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-gallery".
 */
export interface ProjectGallery {
  id: number;
  title: string;
  slug: string;
  /**
   * e.g. "Melbourne, VIC"
   */
  location?: string | null;
  description?: string | null;
  completionDate?: string | null;
  heroImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  product?: (number | null) | Product;
  developer?: string | null;
  numberOfUnits?: number | null;
  /**
   * Builder or developer quote about the project
   */
  testimonial?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'quotes';
        value: number | Quote;
      } | null)
    | ({
        relationTo: 'project-gallery';
        value: number | ProjectGallery;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  excerpt?: T;
  description?: T;
  priceRange?:
    | T
    | {
        from?: T;
        to?: T;
        label?: T;
      };
  status?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        category?: T;
        id?: T;
      };
  floorPlans?:
    | T
    | {
        image?: T;
        label?: T;
        id?: T;
      };
  dimensions?:
    | T
    | {
        length?: T;
        width?: T;
        height?: T;
      };
  bedrooms?: T;
  bathrooms?: T;
  floorArea?: T;
  weight?: T;
  structuralSystem?: T;
  insulationRating?: T;
  nccClassification?: T;
  windRegion?: T;
  balRating?: T;
  applicableStates?: T;
  certifications?:
    | T
    | {
        name?: T;
        type?: T;
        document?: T;
        issueDate?: T;
        expiryDate?: T;
        id?: T;
      };
  optionCategories?:
    | T
    | {
        categoryName?: T;
        selectionType?: T;
        options?:
          | T
          | {
              name?: T;
              description?: T;
              image?: T;
              priceModifier?: T;
              id?: T;
            };
        id?: T;
      };
  sceneTemplate?: T;
  templateThumbnail?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  documentType?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  referenceNumber?: T;
  source?: T;
  status?: T;
  product?: T;
  productTitle?: T;
  productSlug?: T;
  selectedOptions?: T;
  layoutData?: T;
  layoutScreenshot?: T;
  interestCategory?: T;
  contactName?: T;
  contactEmail?: T;
  contactPhone?: T;
  company?: T;
  quantity?: T;
  deliveryState?: T;
  deliveryLocation?: T;
  projectTimeline?: T;
  siteConditions?: T;
  isEstateInquiry?: T;
  numberOfUnits?: T;
  siteAddress?: T;
  modelMix?: T;
  additionalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-gallery_select".
 */
export interface ProjectGallerySelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  location?: T;
  description?: T;
  completionDate?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  product?: T;
  developer?: T;
  numberOfUnits?: T;
  testimonial?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  phone?: string | null;
  email?: string | null;
  location?: string | null;
  companyName?: string | null;
  tagline?: string | null;
  /**
   * Australian Business Number (optional)
   */
  abn?: string | null;
  socialLinks?:
    | {
        platform: 'linkedin' | 'facebook' | 'instagram';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content".
 */
export interface SiteContent {
  id: number;
  hero?: {
    headline?: string | null;
    tagline?: string | null;
    primaryCta?: string | null;
    secondaryCta?: string | null;
  };
  /**
   * Optional background video for the homepage hero. MP4 format recommended. Falls back to poster image or gradient.
   */
  heroVideo?: (number | null) | Media;
  /**
   * Poster image shown while video loads, on mobile, or when no video is set.
   */
  heroPoster?: (number | null) | Media;
  /**
   * Animated statistics displayed on the homepage (e.g. "50+ Designs")
   */
  stats?:
    | {
        /**
         * Label shown below the number (e.g. "Designs")
         */
        label: string;
        /**
         * The number to count up to (e.g. 50)
         */
        value: number;
        /**
         * Optional suffix like "+" or "%" or "m²"
         */
        suffix?: string | null;
        id?: string | null;
      }[]
    | null;
  valueProps?:
    | {
        title: string;
        description: string;
        icon?: ('factory' | 'shield-check' | 'piggy-bank' | 'building-2' | 'clock' | 'truck') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Short paragraph shown on the homepage about section
   */
  aboutSummary?: string | null;
  ctaBanner?: {
    heading?: string | null;
    buttonText?: string | null;
  };
  companyStory?: string | null;
  dealershipModel?: string | null;
  leadership?:
    | {
        name: string;
        role: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  whyModular?: string | null;
  steps?:
    | {
        title: string;
        description: string;
        icon?: ('message-square' | 'pencil-ruler' | 'factory' | 'truck') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  phone?: T;
  email?: T;
  location?: T;
  companyName?: T;
  tagline?: T;
  abn?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content_select".
 */
export interface SiteContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        tagline?: T;
        primaryCta?: T;
        secondaryCta?: T;
      };
  heroVideo?: T;
  heroPoster?: T;
  stats?:
    | T
    | {
        label?: T;
        value?: T;
        suffix?: T;
        id?: T;
      };
  valueProps?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  aboutSummary?: T;
  ctaBanner?:
    | T
    | {
        heading?: T;
        buttonText?: T;
      };
  companyStory?: T;
  dealershipModel?: T;
  leadership?:
    | T
    | {
        name?: T;
        role?: T;
        description?: T;
        id?: T;
      };
  whyModular?: T;
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}